package commands.enums;

public enum CommandType {
    ADDCOMMENT,
    ADDPERSONTOTEAM,
    CHANGEBUGPRIORITY,
    CHANGEBUGSEVERITY,
    CHANGEBUGSTATUS,
    CHANGEFEEDBACKRATING,
    CHANGEFEEDBACKSTATUS,
    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    CHANGESTORYSTATUS,
    CREATEBOARD,
    CREATEBUGINBOARD,
    CREATEFEEDBACKINBOARD,
    CREATESTORYINBOARD,
    CREATEPERSON,
    CREATETEAM,
    SHOWALLPEOPLE,
    SHOWALLTEAMBOARDS,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMS,
    SHOWBOARDACTIVITY,
    SHOWPERSONACTIVITY,
    SHOWTEAMACTIVITY,
    UNASSIGNTASK,
    ASSIGNTASK

}
