package commands.enums;

public enum CommandType {
    ADDCOMMENTCOMMAND,
    ADDPERSONTOTEAMCOMMAND,
    ASSIGNTASKCOMMAND,
    CHANGEBUGPRIORITYCOMMAND,
    CHANGEBUGSEVERITYCOMMAND,
    CHANGEBUGSTATUSCOMMAND,
    CHANGEFEEDBACKRATINGCOMMAND,
    CHANGEFEEDBACKSTATUSCOMMAND,
    CHANGESTORYPRIORITYCOMMAND,
    CHANGESTORYSIZECOMMAND,
    CHANGESTORYSTATUSCOMMAND,
    CREATEBOARDCOMMAND,
    CREATEBUGINBOARDCOMMAND,
    CREATEFEEDBACKINBOARDCOMMAND,
    CREATESTORYINBOARDCOMMAND,
    CREATEPERSONCOMMAND,
    CREATETEAMCOMMAND,
    SHOWALLPEOPLECOMMAND,
    SHOWALLTEAMBOARDSCOMMAND,
    SHOWALLTEAMMEMBERSCOMMAND,
    SHOWALLTEAMSCOMMAND,
    SHOWBOARDACTIVITYCOMMAND,
    SHOWPERSONACTIVITYCOMMAND,
    SHOWTEAMACTIVITYCOMMAND,
    UNASSIGNTASKCOMMAND;

}
