package commands.enums;

public enum CommandType {
    ADDCOMMENT,
    ADDPERSONTOTEAM,
    ASSIGNSTORY,
    ASSIGNBUG,
    CHANGEBUGPRIORITY,
    CHANGEBUGSEVERITY,
    CHANGEBUGSTATUS,
    CHANGEFEEDBACKRATING,
    CHANGEFEEDBACKSTATUS,
    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    CHANGESTORYSTATUS,
    CREATEBOARD,
    CREATEBUGINBOARD,
    CREATEFEEDBACKINBOARD,
    CREATESTORYINBOARD,
    CREATEPERSON,
    CREATETEAM,
    SHOWALLPEOPLE,
    SHOWALLTEAMBOARDS,
    SHOWALLTEAMMEMBERS,
    SHOWALLTEAMS,
    SHOWBOARDACTIVITY,
    SHOWPERSONACTIVITY,
    SHOWTEAMACTIVITY,
    UNASSIGNBUG,
    UNASSIGNSTORY

}
